### ISSUE TITLE
What is the difference between this plugin and twilight.nvim

### ISSUE THREAD

**Issue by RayJameson** [zbirenbaum/neodim#32]
Title says it all

**Comment by zbirenbaum** [comment]
The plugins have an entirely different purpose. Twilight focuses the current code region and dims the rest of the editor. Neodim gets information from the lsp about things like variables, functions or imports that haven't been referenced after declaration and dims those particular tokens.

There are one or two other plugins that do this but neodim is by far the highest performance one to my knowledge. It reimplements and embeds this behavior into the treesitter highlighter itself, updating in time with all other highlights. It is only limited by how long the delay after typing you configure the lsp diagnostics to be refreshed/how fast your lsp is.

Some languages don't work perfectly due to not adhering to the lsp spec or messages not matching expected regexes. I mostly wrote this for myself so languages I write infrequently aren't my top priority, but I always take PRs.

**Comment by RayJameson** [comment]
Thanks for your answer!
