### ISSUE TITLE
[Feature] Add the ability to disable LSP signs for unused variables

### ISSUE THREAD

**Issue by akinsho** [zbirenbaum/neodim#4]
Hi @zbirenbaum,

Thanks for making this plugin, I've been using https://github.com/NarutoXY/dim.lua for a while and enjoying the functionality. I just submitted this PR https://github.com/NarutoXY/dim.lua/pull/11, but the author has just mentioned they plan to archive the project, so I'm wondering if you'd be interested in providing this functionality which is in short the ability to hide other lsp decorations specifically `signs` in the case of my PR. I think it goes into some detail about the desired functionality if you could take a look 🙏🏿

**Comment by zbirenbaum** [comment]
Hi Akinsho, this is actually a functionality I was thinking of adding just earlier today when I was fixing it to work with go. I'd be more than happy to add support for removing signs.

Unfortunately, though, I can't seem to get just the signs for the unused variables to disappear. Trying to do what you did in that PR only removes all of the signs for me, and the docs state that should be the case, only the buffer field is supplied. Here's what I'm referring to in case I missed something:
```
local id = lsp_ns.user_data[ns_to_clear]
if type(id) == "string" then
  vim.fn.sign_unplace(id, { buffer = vim.api.nvim_get_current_buf() })
```

If removing all signs happens to be what you want, you can just set `signs=false,` in the `vim.diagnostic.config` function I describe in the readme.

I tried overwriting the signs using `buf_set_extmark`, but while that did let me write over other signs, like gitsigns (which notably also uses extmarks), it did not let me overwrite the signs defined by the lsp handler.

I then tried using the corresponding vim functions instead, in an attempt to see what could be going on, but `vim.fn.sign_getplaced(bufnr)` always gives me a an empty table for the buffer.I'm not sure if its a bug in my build or something, but the behavior here seems a bit off.

I think the only way to do this would be to implement an lsp sign handler that replaces the default one using extmarks, which would then be easily overridable. Its not super hard to do inside of the handlers here, as I could just set them as I iterate the diagnostics, and I'll try it out tomorrow. Realistically, they should probably be set with the extmark api in the diagnostic runtime code considering everything else in that module makes use of it, and extmarks are a lot less buggy and easier to work with. Since I'll essentially be writing exactly what I would have to in the upstream code, I'll probably just PR it, and I'll the ability to use a function like for the virt text when I do.

Sorry for the essay! Please let me know if you notice anything here that doesn't seem right or if I'm encountering a bug that isn't in other builds, as I build from source.

**Comment by akinsho** [comment]
@zbirenbaum think you might be right about my PR removing all signs tbh I don't think I noticed when I tested it. Regarding a solution, looking at the docs for `sign_unplace` it seems that if you had the ID of the original sign you could remove a specific sign I guess if we knew how nvim sets the IDs in core e.g. does it already use the line number as the ID maybe the sign unplace call could just use the lnum. 

The alternative of replacing the handler would also work, but I guess I wonder how it would work if a user has already replaced the handler themselves which I have for signs so that it only places one sign per line rather than n number of signs per diagnostic which I find too noisy. I guess it would probably work fine since before or after as long as both handlers were called it would be fine.

Re. the extmark implementation seems like a good shout to eventually move to that but that's probably a fair bit of work beyond just this issue but would be great for the community I think 🤷🏿

**Comment by zbirenbaum** [comment]
I downloaded the original dim.lua and it did seem to replace them all. For your particular purposes, since you don't want any signs, I would say just set signs=false in the vim.diagnostic.config function. You won't get any sign flashes associated with updating that way either.

> it seems that if you had the ID of the original sign you could remove a specific sign

I messed around a bunch with the id field but there's no value for which it works. I think that's a bug in upstream caused by the vim api. There's no id entry present for those signs in any of the functions the docs say are supposed to return the id. 

> The alternative of replacing the handler would also work, but I guess I wonder how it would work if a user has already replaced the handler themselves which I have for signs so that it only places one sign per line rather than n number of signs per diagnostic

Extmark based signs are good because you can namespace them to clear or show them at will, and assign them priorities that will be respected. The short answer to this would be "however the user wants it work is how it would" since they can just clear any namespaces they don't want and assign whatever signs they would like to different namespaces.

I'm not a fan of hard coding functionality like that without the ability to override so I would probably just let the user pass in their own function to override my defaults.

Right now, diagnostic signs will always write over gitsigns, but if they were to be implemented with extmarks, a user could easily change that. Taking it a step further, a user could set it up so that signs for unused variables _do_ show up, but _only_ if there isn't a git sign present for that line, while signs for more severe diagnostics could overwrite git signs.

**Comment by akinsho** [comment]
> For your particular purposes, since you don't want any signs, I would say just set signs=false in the vim.diagnostic.config function. You won't get any sign flashes associated with updating that way either.

Just to clarify I don't want to clear all signs only the ones for the unused diagnostic

**Comment by zbirenbaum** [comment]
> > For your particular purposes, since you don't want any signs, I would say just set signs=false in the vim.diagnostic.config function. You won't get any sign flashes associated with updating that way either.
> 
> 
> 
> Just to clarify I don't want to clear all signs only the ones for the unused diagnostic

Ah, sorry I misunderstood. I'll see what I can do about implementing it in the next day or so, it shouldn't take too long now that I know exactly what I need to do to make it work.

**Comment by zbirenbaum** [comment]
This ended up being way easier than I thought, I just redefined all the diagnostic handlers such that they filter the diagnostic field and then call the old handler with the filtered diagnostics. 

It's annoying that it means there will be two passes over all non-unused diagnostics to apply the handler function, but they are so fast it doesn't matter in the slightest, so I'm not too concerned. I think that the extmarks is a good idea to upstream, but this is pretty great as a bug free simple solution.

**Comment by akinsho** [comment]
Awesome just tried it out and it works great 🚀 , thanks 👍🏿
